System:
    Login:
        Password:
            MinLength: 8
            MaxLength: 16
            MinUpper: 2
            MinDigits: 2
            MinSpecial: 2
            Alg: Uber
        UserName:
            MinLength: 6
            MaxLength: 20
